package callofproject.dev.adroid.app.util

const val LOGIN_PAGE = "LOGIN_PAGE"
const val REGISTER_PAGE = "REGISTER_PAGE"
const val FORGOT_PASSWORD_PAGE = "FORGOT_PASSWORD_PAGE"
const val MAIN_PAGE = "MAIN_PAGE"
const val PROJECT_DETAILS_PAGE = "PROJECT_DETAILS_SCREEN"
const val PROJECT_OVERVIEW_PAGE = "PROJECT_OVERVIEW_PAGE"
const val PROFILE_PAGE = "PROFILE_PAGE"
const val NOTIFICATION_PAGE = "NOTIFICATION_PAGE"
const val MY_PROJECTS_PAGE = "MY_PROJECTS_PAGE"