package callofproject.dev.core.navigation

object Route {
    const val LOGIN_PAGE = "LOGIN_PAGE"
    const val REGISTER_PAGE = "REGISTER_PAGE"
    const val MAIN_PAGE = "MAIN_PAGE"
    const val PROJECT_DETAILS_PAGE = "PROJECT_DETAILS_SCREEN"
    const val PROJECT_OVERVIEW_PAGE = "PROJECT_OVERVIEW_PAGE"
    const val PROFILE_PAGE = "PROFILE_PAGE"
    const val NOTIFICATION_PAGE = "NOTIFICATION_PAGE"
    const val MY_PROJECTS_PAGE = "MY_PROJECTS_PAGE"
    const val UPSERT_ABOUT_ME_PAGE = "EDIT_ABOUT_ME_PAGE"
    const val UPSERT_EDUCATION_PAGE = "EDIT_EDUCATION_PAGE"
    const val UPSERT_EXPERIENCE_PAGE = "EDIT_EXPERIENCE_PAGE"
    const val UPSERT_COURSE_PAGE = "EDIT_COURSE_PAGE"
    const val UPSERT_PROJECT_PAGE = "EDIT_PROJECT_PAGE"
    const val UPSERT_LINK_PAGE = "EDIT_LINK_PAGE"
    const val PROJECT_DISCOVERY_PAGE = "PROJECT_DISCOVERY_PAGE"
    const val TASKS_PAGE = "TASKS_PAGE"
}